# permissions for end users to view configwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configwatcher-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: configwatcher-go-operator
    app.kubernetes.io/part-of: configwatcher-go-operator
    app.kubernetes.io/managed-by: kustomize
  name: configwatcher-viewer-role
rules:
- apiGroups:
  - tutorials.github.com
  resources:
  - configwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tutorials.github.com
  resources:
  - configwatchers/status
  verbs:
  - get
