---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - tutorials.github.com
  resources:
  - configwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tutorials.github.com
  resources:
  - configwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - tutorials.github.com
  resources:
  - configwatchers/status
  verbs:
  - get
  - patch
  - update
