apiVersion: v1
imagePullSecrets:
- name: my-secret
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: configwatcher-go-operator
    app.kubernetes.io/part-of: configwatcher-go-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
secrets:
- name: my-secret
